# Generated by Django 3.1.1 on 2021-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210304_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user_image.png', upload_to='user_profile_pics'),
        ),
    ]
